#! /bin/sh
# Author: g3k

export PATH="$HOME/.config/bspwm/scripts:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1


pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV V VI 


bspc config top_padding           30
bspc config bottom_padding        3
bspc config right_padding         3
bspc config left_padding          3
bspc config window_gap 9  
bspc config split_ratio           0.505
bspc config single_monocle        true
bspc config automatic_scheme      longest_side
bspc config initial_polarity      second_child
bspc config removal_adjustment    true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config border_width          0
bspc rule -a FloatingTerm state=floating center=true
bspc config external_rules_command "${HOME}/.config/bspwm/scripts/rules"
bspc rule -a kitty:FloatingTerm state=floating center=true


"$HOME/.config/bspwm/scripts/workspaces"
"$HOME/.config/bspwm/scripts/targetip"

pgrep -x dunst >/dev/null || dunst &


sleep 2
pidof picom >/dev/null || picom --config "$HOME/.config/picom/picom.conf" -b &

WALLPAPER_NUM=$((RANDOM % 3 + 1))
feh --bg-fill "${HOME}/.config/wallpapers/img${WALLPAPER_NUM}.png"
polybar -c ~/.config/polybar/config.ini envertex-bar &



rm -f \
  "$HOME/.zsh_history" \
  "$HOME/.bash_history" \
  "$HOME/.local/share/fish/fish_history" 2>/dev/null