#!/usr/bin/env bash
# Author: g3k

CACHE="$HOME/.cache/target_ip"

if [[ -f "$CACHE" ]]; then
  TARGET=$(tr -d '[:space:]' < "$CACHE")
  if [[ -n "$TARGET" ]]; then
    echo "󰓾 $TARGET"
    exit 0
  fi
fi

echo "󰓾 No target"

