#!/usr/bin/env bash

CACHE="$HOME/.cache/target_ip"

# Sin argumentos → No target
if [[ -z "$1" ]]; then
  rm -f "$CACHE"
  polybar-msg hook target 1 >/dev/null 2>&1
  exit 0
fi

# Con argumento → set target
echo "$1" > "$CACHE"
polybar-msg hook target 1 >/dev/null 2>&1
