#!/bin/sh
# Author: g3k

ICON_DIR="$HOME/.config/bspwm/scripts/images"
VOL_ICON="$ICON_DIR/vol.png"
MUTE_ICON="$ICON_DIR/mute.png"

# Mostrar notificación
notify_volume() {
    local icon="$1"
    local text="$2"
    dunstify \
        -r 9999 \
        -u low \
        -t 1500 \
        -h string:x-dunst-stack-tag:volume \
        -h int:transient:1 \
        -i "$icon" "$text"
}

# Obtener y mostrar volumen
show_volume() {
    vol=$(pamixer --get-volume)
    mute=$(pamixer --get-mute)

    if [ "$mute" = "true" ] || [ "$vol" -eq 0 ]; then
        notify_volume "$MUTE_ICON" "Silenciado"
    else
        notify_volume "$VOL_ICON" "Volumen: ${vol}%"
    fi
}

# Subir/bajar volumen
adjust_volume() {
    pamixer --unmute
    pamixer --allow-boost --set-limit 150 "$@"
    show_volume
}

# Mute
toggle_mute() {
    pamixer --toggle-mute
    show_volume
}

# Ejecutar
case "$1" in
    --get)    pamixer --get-volume-human ;;
    --inc)    adjust_volume -i 5 ;;
    --dec)    adjust_volume -d 5 ;;
    --toggle) toggle_mute ;;
    *)        echo "$(pamixer --get-volume)%" ;;
esac
